default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  username: root
  password: Pepe0909

development:
  <<: *default
  database: yokozuna_development
  socket: /tmp/mysql.sock

test:
  <<: *default
  database: db/yokozuna.sqlite3

production:
  <<: *default
  database: db/yokozuna
